### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by ChamNouki** [azlux/pymumble#62]
Trying to install latest version of pymumble (to test #56 and #57) but got an installation error : 

requirements.txt
```txt
opuslib==2.0.0
protobuf==3.4.0
git+https://github.com/azlux/pymumble#egg=pymumble
```

```
$> pip install -r requirements.txt
Processing [...]/pip/wheels/e5/ba/d4/0e81231a9797fbb262ae3a54fd761fab850db7f32d94a3283a/opuslib-2.0.0-py3-none-any.whl
Collecting protobuf==3.4.0
  Using cached protobuf-3.4.0-py2.py3-none-any.whl (375 kB)
Collecting pymumble
  Cloning https://github.com/azlux/pymumble to /private/var/folders/zz/z3n5q0c115n7_27cd_qmtz5h0000gn/T/pip-install-wapr0cop/pymumble
  Running command git clone -q https://github.com/azlux/pymumble /private/var/folders/zz/z3n5q0c115n7_27cd_qmtz5h0000gn/T/pip-install-wapr0cop/pymumble
    ERROR: Command errored out with exit status 1:
     command: /Users/thibaut/Documents/GitHub/Mumgram/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zz/z3n5q0c115n7_27cd_qmtz5h0000gn/T/pip-install-wapr0cop/pymumble/setup.py'"'"'; __file__='"'"'/private/var/folders/zz/z3n5q0c115n7_27cd_qmtz5h0000gn/T/pip-install-wapr0cop/pymumble/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/zz/z3n5q0c115n7_27cd_qmtz5h0000gn/T/pip-install-wapr0cop/pymumble/pip-egg-info
         cwd: /private/var/folders/zz/z3n5q0c115n7_27cd_qmtz5h0000gn/T/pip-install-wapr0cop/pymumble/
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zz/z3n5q0c115n7_27cd_qmtz5h0000gn/T/pip-install-wapr0cop/pymumble/setup.py", line 2, in <module>
        from pymumble_py3.constants import PYMUMBLE_VERSION
      File "/private/var/folders/zz/z3n5q0c115n7_27cd_qmtz5h0000gn/T/pip-install-wapr0cop/pymumble/pymumble_py3/__init__.py", line 3, in <module>
        from .mumble import Mumble
      File "/private/var/folders/zz/z3n5q0c115n7_27cd_qmtz5h0000gn/T/pip-install-wapr0cop/pymumble/pymumble_py3/mumble.py", line 12, in <module>
        from . import users
      File "/private/var/folders/zz/z3n5q0c115n7_27cd_qmtz5h0000gn/T/pip-install-wapr0cop/pymumble/pymumble_py3/users.py", line 5, in <module>
        from . import soundqueue
      File "/private/var/folders/zz/z3n5q0c115n7_27cd_qmtz5h0000gn/T/pip-install-wapr0cop/pymumble/pymumble_py3/soundqueue.py", line 6, in <module>
        import opuslib
    ModuleNotFoundError: No module named 'opuslib'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by azlux** [comment]
Please use the new pypi pymumble version (https://pypi.org/project/pymumble/)

On your log, I see `Collecting protobuf==3.4.0`and `Collecting pymumble` but not `Collecting opuslib` even if it's present into your `requirements.txt`

What is your pip version ? And your python3 version ?

**Comment by ChamNouki** [comment]
> Please use the new pypi pymumble version (https://pypi.org/project/pymumble/)

Oh yeay ! :D 👍 and it solved the installation issue.

> What is your pip version ? And your python3 version ?

Python 3.7.7
pip 20.0.2

>On your log, I see Collecting protobuf==3.4.0and Collecting pymumble but not Collecting opuslib even if it's present into your requirements.txt

Yup that's strange but opuslib seems to be install locally from somewhere on my computer 
```
Processing [...]/pip/wheels/e5/ba/d4/0e81231a9797fbb262ae3a54fd761fab850db7f32d94a3283a/opuslib-2.0.0-py3-none-any.whl
```
