### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by farooqkz** [azlux/pymumble#73]
```Traceback (most recent call last):
  File "kumble.py", line 29, in <module>
    M.sound_output.add_sound(buffer)
  File "/home/farooqkz/pymumble-1.2/pymumble_py3/soundoutput.py", line 159, in add_sound
    samples = int(self.encoder_framesize * PYMUMBLE_SAMPLERATE * 2 * self.channels)  # number of samples in an encoder frame
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```
And here's my code:
```
import subprocess as sp
import socket
import pymumble_py3 as pm
import random
import sys
import tempfile
import soundfile as sf

sock = socket.socket()
sock.bind(("192.168.1.103", 2049))
sock.listen()

while 1:
    csock, addr = sock.accept()
    print(addr, file=sys.stderr)
    num = str(random.randint(1000, 10000))
    nick = "Chickenkiller" + num
    M = pm.Mumble("127.0.0.1", nick, password="(Farooq's password)", reconnect= True)
    M.start()
    buffer = b""
    while not buffer.endswith(b"BYEBYEBYE"):
        buf = csock.recv(512)
        buffer = tempfile.SpooledTemporaryFile()
        buffer.write(buf)
        buffer.seek(0)
        cmd = ("ffmpeg", "-f", "s16le", "-ar", "48000", "-i", "-", "-")
        proc = sp.Popen(cmd, stdin=buffer, stdout=sp.PIPE, stderr=sp.DEVNULL)
        buffer = proc.stdout.read()
        M.sound_output.add_sound(buffer)
```

**Comment by azlux** [comment]
Hi, in "/home/farooqkz/pymumble-1.2/pymumble_py3/soundoutput.py", line 158, can you print all 3 variables : `self.encoder_framesize`,  `PYMUMBLE_SAMPLERATE` and `self.channels` ?
None of them should be `None`

**Comment by azlux** [comment]
And after the line `M.start()` you should add a `M.is_ready()`. Maybe the codec isn't started yet.

**Comment by azlux** [comment]
Is this issue can be closed ? Have you everything working ?

**Comment by farooqkz** [comment]
Yeah let it be closed for now :)
